---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: install tomcat
    yum: name=tomcat state=present
  - name: start tomcat
    service: name=tomcat state=started
  - name: install docker
    yum: name=docker state=present
  - name: start docker
    service: name=docker state=started
  - name: install git
    yum: name=git state=present
  - name: pull docker image
    services:
      image: addressbook
      source: https://hub.docker.com/repository/docker/ruchira1394/addressbook 
      dest: /tmp/mygitrepo5
  - name: build docker file
    command: chdir=/tmp/mygitrepo5 docker build -t myadd:ansible2 .
  - name: create container
    command: docker run -itd -P myadd:ansible2
