---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: install tomcat
    yum: name=tomcat state=present
  - name: start tomcat
    service: name=tomcat state=started
  - name: install docker
    yum: name=docker state=present
  - name: start docker
    service: name=docker state=started
  - name: pull an image
    command: docker pull ruchira1394/addressbook:image
  - name: delete container if myapp is present
    command: docker rm -f myapp 
  - name: create container
    command: docker run -itd --name myapp -P ruchira1394/addressbook:image
